### PR TITLE
Sol v0.8

### PR DESCRIPTION
**Pull request by RyanRHall**
This PR does the following:
* upgrades the strings library to sol v0.8
* updates the ds-test submodule to latest version (needed for the unlocked pragma)
* adds a CI workflow (to hopefully make future changes easier)

### CODE REVIEW

**Review by zbcoding — APPROVED** [review]
Nice
A few new additions building on https://github.com/Arachnid/solidity-stringutils/pull/45/files

**Comment by tempe-techie** [comment]
@RyanRHall I'm getting this warning in the hardhat console:

```
Warning: This declaration shadows an existing declaration.

45 |     function memcpy(uint dest, uint src, uint len) private pure {
```

This is because the `len` attribute has the same name as the function `len()`.

The code still works, nothing serious, but it would make sense to rename the `len` attribute in `memcpy` to `_len` or something else.

**Comment by tempe-techie** [comment]
Also adding `SPDX-License-Identifier` would be beneficial, but this is something @Arachnid needs to decide since he wrote the library.

**Comment by hellwolf** [comment]
when merge?

**Review by Arachnid — APPROVED** [review]

**Comment by hellwolf** [comment]
thank you @Arachnid !

**Pull request merged**
